### ISSUE TITLE
Add document resize handler

### ISSUE THREAD

**Issue by davestewart** [MarxJiao/vue-proportion-directive#1]
Great directive!

Came up first in a google search and saves me writing it!

https://www.google.com/search?q=vue+porportional+directive&oq=vue+porportional+directive&aqs=chrome..69i57j33.6146j0j7&sourceid=chrome&ie=UTF-8

Could do with a document resize handler though.

**Comment by davestewart** [comment]
Added PR: #2

**Comment by MarxJiao** [comment]
Good job. I merged your PR and published `vue-proportion-directive@1.1.0`.
